spring:
  application:
    name: HIBERNATE-CRUD-EXAMPLE
  datasource:
    username: scott
    password: India123
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
      

  